"""update connections table

Revision ID: 45d9441b7f65
Revises: 8695aa1fc724
Create Date: 2025-11-20 01:01:26.140295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '45d9441b7f65'
down_revision: Union[str, Sequence[str], None] = '8695aa1fc724'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('port_connections')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('port_connections',
    sa.Column('port_a_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('port_a_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('port_b_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('port_b_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('distance_km', mysql.FLOAT(), nullable=False),
    sa.Column('time_hours', mysql.FLOAT(), nullable=False),
    sa.Column('cost_usd', mysql.FLOAT(), nullable=False),
    sa.Column('route_type', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('is_restricted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
