"""create exports table

Revision ID: b654eb9742d1
Revises: a903cf9543c3
Create Date: 2025-11-21 00:40:56.174577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b654eb9742d1'
down_revision: Union[str, Sequence[str], None] = 'a903cf9543c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exports',
                    sa.Column('id', sa.String(length=36), primary_key=True, nullable=False),
                    sa.Column('comercial_description', sa.String(length=255), nullable=False),
                    sa.Column('transportation_mode', sa.String(length=255), nullable=False),
                    sa.Column('us_fob', sa.Float(), nullable=False),
                    sa.Column('gross_weight', sa.Float(), nullable=False),
                    sa.Column('net_weight', sa.Float, nullable=False),
                    sa.Column('unit', sa.String(length=255), nullable=False),
                    sa.Column('quantity', sa.Float, nullable=False),
                    sa.Column('optimized_route_id', sa.String(length=36),
                              sa.ForeignKey('optimal_routes.id', ondelete='CASCADE'), nullable=False),
                    sa.Column('user_id', sa.String(length=36), sa.ForeignKey('users.id', ondelete='CASCADE'),
                              nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False)
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('port_connections',
    sa.Column('port_a_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('port_a_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('port_b_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('port_b_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('distance_km', mysql.FLOAT(), nullable=False),
    sa.Column('time_hours', mysql.FLOAT(), nullable=False),
    sa.Column('cost_usd', mysql.FLOAT(), nullable=False),
    sa.Column('route_type', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('is_restricted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('optimal_routes',
    sa.Column('origin_port_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('origin_port_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('destination_port_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('destination_port_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('route_mode', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('total_distance', mysql.FLOAT(), nullable=False),
    sa.Column('total_time', mysql.FLOAT(), nullable=False),
    sa.Column('total_cost', mysql.FLOAT(), nullable=False),
    sa.Column('visited_ports', mysql.JSON(), nullable=False),
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('full_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('hashed_password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###
