"""update ports table

Revision ID: d1da07759e52
Revises: 45d9441b7f65
Create Date: 2025-11-20 16:18:07.490811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd1da07759e52'
down_revision: Union[str, Sequence[str], None] = '45d9441b7f65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ports', sa.Column('capacity', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ports', 'capacity')

    op.create_table('users',
    sa.Column('full_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('hashed_password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)

    op.create_table('port_connections',
    sa.Column('port_a_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('port_a_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('port_b_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('port_b_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('distance_km', mysql.FLOAT(), nullable=False),
    sa.Column('time_hours', mysql.FLOAT(), nullable=False),
    sa.Column('cost_usd', mysql.FLOAT(), nullable=False),
    sa.Column('route_type', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('is_restricted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
